apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: rbravo
spec:
  containers:
    - name: web
      image: nginx:stable-alpine
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
