name: "Building docker image"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Building & Pushing image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "hello"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login to GCR
        uses: docker/login-action@v1.10.0
        with:
          registry: us-east4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push to GCR
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./hello-app
          no-cache: true
          push: true
          tags: |
            us-east4-docker.pkg.dev/clever-devops-testings/hello-app/${{ env.IMAGE_NAME }}:latest
            us-east4-docker.pkg.dev/clever-devops-testings/hello-app/${{ env.IMAGE_NAME }}:${{ github.sha }}